language: python
python:
  - 3.5
services:
  - docker

#before_install:
#  - docker build -t local/primes-calc .

# Does the container run, and start the Python primes script?
script:
  - docker-compose run --rm primes-calc 5
